ex_cli_applications/trustm_cert.c, ex_cli_applications/trustm_data.c, ex_cli_applications/trustm_ecc_keygen.c, ex_cli_applications/trustm_ecc_sign.c, ex_cli_applications/trustm_ecc_verify.c, ex_cli_applications/trustm_hkdf.c, ex_cli_applications/trustm_hmac.c, ex_cli_applications/trustm_hmac_verify_Auth.c, ex_cli_applications/trustm_metadata.c, ex_cli_applications/trustm_monotonic_counter.c, ex_cli_applications/trustm_protected_update.c, ex_cli_applications/trustm_protected_update_aeskey.c, ex_cli_applications/trustm_protected_update_data.c, ex_cli_applications/trustm_protected_update_ecckey.c, ex_cli_applications/trustm_protected_update_rsakey.c, ex_cli_applications/trustm_read_data.c, ex_cli_applications/trustm_read_status.c, ex_cli_applications/trustm_readmetadata_data.c, ex_cli_applications/trustm_readmetadata_private.c, ex_cli_applications/trustm_readmetadata_status.c, ex_cli_applications/trustm_rsa_dec.c, ex_cli_applications/trustm_rsa_enc.c, ex_cli_applications/trustm_rsa_keygen.c, ex_cli_applications/trustm_rsa_sign.c, ex_cli_applications/trustm_rsa_verify.c, ex_cli_applications/trustm_symmetric_dec.c, ex_cli_applications/trustm_symmetric_enc.c, ex_cli_applications/trustm_symmetric_keygen.c
Description
I would like to add a new options which by enabling it  shall demonstrate how muc of a real time an optiga related function call consumes.
Context
Raspberry Pi 3B
=> Add performance option

ex_cli_applications/trustm_hmac_verify_Auth.c, ex_protected_update_data_set/Linux/Makefile, scripts/protected_update_ecckey/protected_update_ecc_provisioning_step1.sh, trustm_helper/trustm_helper.c
Description
This pull request fixes some typos in different files.
It additionally introduces AARCH64 as compile-platform to the protected-update scripts.
=> fix some typos

Makefile
Description
Related Issue
Context
=> fixed makefile error for arm64

scripts/openssl_trustm_as_CA/README.md, scripts/openssl_trustm_as_CA/clean.sh, scripts/openssl_trustm_as_CA/openssl.cnf, scripts/openssl_trustm_as_CA/trustm_ca_gen_cert.sh
Description
Related Issue
Context
=> Add script to use Optiga Trust M as HSM to issue certficate

0001-trust_m_lib.patch
Description
Related Issue
Context
=> 1)fixed the gpio opening error for linux

ex_cli_applications/trustm_ecc_sign.c, scripts/misc/BrainPool256_384_test.sh, scripts/misc/BrainPool512_test.sh, scripts/misc/clean_files.sh, scripts/misc/ecc384_test.sh, scripts/misc/ecc521_test.sh, trustm_helper/include/trustm_helper.h, trustm_helper/trustm_helper.c
Description
Related Issue
Context
=> Provider dev

provider-scripts/ec_keygen_and_sign/ecc521_test.sh, provider-scripts/ec_keygen_and_sign/step_1_cleanup.sh, trustm_provider/trustm_provider_common.h, trustm_provider/trustm_provider_signature.c
Description
Related Issue
Context
=> Add ECC p521 signature pre-padding check 

0001-trust_m_lib.patch, ex_cli_applications/trustm_ecc_sign.c, ex_cli_applications/trustm_ecc_verify.c, ex_cli_applications/trustm_read_data.c, ex_cli_applications/trustm_read_status.c, ex_cli_applications/trustm_readmetadata_data.c, ex_cli_applications/trustm_readmetadata_private.c, ex_cli_applications/trustm_readmetadata_status.c, provider_installation_script.sh, scripts/misc/BrainPool256_384_test.sh, scripts/misc/BrainPool512_test.sh, scripts/misc/ecc256_test.sh, scripts/misc/ecc384_test.sh, scripts/misc/ecc521_test.sh, trustm_helper/include/trustm_helper.h, trustm_helper/trustm_helper.c
Description
Related Issue
Context
=> Added SHA384/512 for ECC Sign/Verify for Provider dev branch

provider-scripts/rsa_keygen_and_decrypt/RSA_openssl_enc_Trust_M_dec.sh, trustm_provider/trustm_keymgmt_rsa.c, trustm_provider/trustm_provider_asym_rsa.c
1)Fixed the issue for RSA Decryption using Trust M provider
=> 1)Fixed the issue for RSA Decryption using Trust M provider

trustm_provider/trustm_provider.c, trustm_provider/trustm_provider_common.h, trustm_provider/trustm_rand.c
=> 1)Tidy up the code

provider-scripts/rsa_keygen_and_decrypt/RSA_encrypt_decrypt_concurrency_test.sh, provider_installation_script.sh, trustm_provider/trustm_keymgmt_rsa.c, trustm_provider/trustm_provider_asym_rsa.c, trustm_provider/trustm_provider_common.h, trustm_provider/trustm_provider_signature.c
1)Added test script for RSA Encrypt/Decrypt concurrency test using Trust M provider
2)Added more debugging message printout
=> Added test script for RSA Encrypt/Decrypt concurrency test using Trust M provider

trustm_provider/trustm_provider_signature.c, trustm_provider/trustm_provider_store_object.c
=> Minor code modification

ex_cli_applications/trustm_read_status.c, ex_cli_applications/trustm_readmetadata_status.c
1)Updated the OID list for trustm_read_status.c and trustm_readmetadata_status.c
=> 1)Updated the OID list for trustm_read_status.c and trustm_readmetadata_status.c 

provider-scripts/Server_Client_keyfile/step1_genetrate_ecc_pem_files.sh, provider-scripts/Server_Client_keyfile/step3_start_ecc_clients.sh, provider-scripts/ec_sign_verify_pem_files/ecc_sign_verify_with_pem.sh, trustm_provider/trustm_provider_store_object.c
1)Added Dummy Private key pem file generation with OID information
2)Updated the scripts for ecc_sign_verify_with_pem.sh
3)Updated the test scripts for Server Client Communication
=> 1)Added Dummy Private key pem file generation with OID information

provider-scripts/Server_Client_keyfile/step1_genetrate_ecc_pem_files.sh, provider-scripts/Server_Client_keyfile/step3_start_ecc_clients.sh
1) Updated the test scripts for Server Client using customized key file
=> 1) Updated the test scripts for Server Client using customized key file

trustm_provider/trustm_digest.c
1)Fixed the issue when using Trust M V1 on server side for Server Client communication
=> 1)Fixed the issue when using Trust M V1 on Server side for Server Client communication

trustm_provider/trustm_provider.c, trustm_provider/trustm_provider_common.h, trustm_provider/trustm_provider_core.c, trustm_provider/trustm_rand.c
1)Resolved the issue for random number generator used by curl
=> 1)Resolved the issue for random number generator used by curl

ex_cli_applications/trustm_chipinfo.c
**Description**
Add identifier for eSW v3.02.2564 to "trustm_chipinfo" command
=> Add identifier for eSW Update 3.02

README.md, trustm_provider/trustm_keymgmt_rsa.c, trustm_provider/trustm_provider_signature.c, trustm_provider/trustm_provider_store_object.c
1)Updated README.md
2)Added more debugging message print out
=> 1)Updated README.md

README.md, trustm_provider/trustm_keymgmt_rsa.c, trustm_provider/trustm_provider_signature.c, trustm_provider/trustm_provider_store_object.c
1)Updated README.md
2)Added more debugging message print out
=> 1)Updated README.md (#92)

trustm_provider/trustm_provider_store_object.c
1)Added E0E0 pre-provisioned key/cert support for key pem file export
=> 1)Added E0E0 pre-provisioned key/cert support for key pem file export

trustm_provider/trustm_provider_store_object.c
=> 1)Added Error Handling 
